permissions:
  contents: write

on: push
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    if: github.repository == 'aiwolfdial/aiwolf-nlp-agent'
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "## 目次"
          TARGET_PATHS: "README.md"
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "## Table of Contents"
          TARGET_PATHS: "README.en.md"
